name: Deployment

on:
  workflow_dispatch:
    inputs:
      groupId_old:
        description: 'The old/original groupId'
        required: true
        type: string
        default: 'software.xdev'
      groupId_new:
        description: 'The new groupId'
        required: true
        type: string
        default: 'software.xdev'
      artifactId_old:
        description: 'The old/original artifactId'
        required: true
        type: string
      artifactId_new:
        description: 'The new artifactId'
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Sed pom.xml
      run: |
        sed -i "s@SED_GROUPID_OLD@${{ inputs.groupId_old }}@g" pom.xml
        sed -i "s@SED_GROUPID_NEW@${{ inputs.groupId_new }}@g" pom.xml
        sed -i "s@SED_ARTIFACT_ID_OLD@${{ inputs.artifactId_old }}@g" pom.xml
        sed -i "s@SED_ARTIFACT_ID_NEW@${{ inputs.artifactId_new }}@g" pom.xml
        sed -i "s@SED_VERSION@${{ inputs.version }}@g" pom.xml
        cat pom.xml
    
    - name: Set up JDK OSSRH
      uses: actions/setup-java@v4
      with: # running setup-java again overwrites the settings.xml
        distribution: 'temurin'
        java-version: '17'
        server-id: ossrh
        server-username: S01_OSS_SONATYPE_MAVEN_USERNAME
        server-password: S01_OSS_SONATYPE_MAVEN_TOKEN
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Publish to OSSRH
      run: mvn -B deploy -Possrh
      env:
        S01_OSS_SONATYPE_MAVEN_USERNAME: ${{ secrets.S01_OSS_SONATYPE_MAVEN_USERNAME }}
        S01_OSS_SONATYPE_MAVEN_TOKEN: ${{ secrets.S01_OSS_SONATYPE_MAVEN_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
