name: Deployment

on:
  workflow_dispatch:
    inputs:
      groupId_old:
        description: 'The old/original groupId'
        required: true
        type: string
        default: 'com.xdev-software'
      groupId_new:
        description: 'The new groupId'
        required: true
        type: string
        default: 'software.xdev'
      artifactId:
        required: true
        type: string
      version:
        required: true
        type: string
      url:
        description: 'Url to where the source code is hosted'
        required: true
        type: string
        default: 'https://github.com/xdev-software/<REPO_HERE>'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Sed pom.xml
      run: echo "TODO"
    
    - name: Set up JDK OSSRH
      uses: actions/setup-java@v4
      with: # running setup-java again overwrites the settings.xml
        distribution: 'temurin'
        java-version: '17'
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Publish to OSSRH
      run: mvn -B deploy -Possrh
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
